### PR TITLE
Update URLs after repo move.

### PR DESCRIPTION
**Pull request by vext01**

### CODE REVIEW

**Comment by ltratt** [comment]
Is it just me or is bors not doing anything?

**Comment by ltratt** [comment]
@vext01 Something is stuck...

**Comment by vext01** [comment]
Ah, looks like I need to re-setup bors since the repo moved. I'll get to this shortly, and it may require a buildbot change too.

**Comment by vext01** [comment]
bors ping

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
@ltratt ready to go

**Pull request merged**
