### PR TITLE
Try to clarify expectations around commit message documentation.

### PR DESCRIPTION
**Pull request by ltratt**
[Will assign @gabi-250 once she's a member of the ykjit team]

### CODE REVIEW

**Review by gabi-250 — APPROVED** [review]

**Comment by ltratt** [comment]
@gabi-250 If you're happy you can do the bors honours!

**Comment by gabi-250** [comment]
Will do (for a moment I forgot we use bors!)

**Comment by ltratt** [comment]
Hmph, apparently I need to do something. Bear with.

**Comment by ltratt** [comment]
Try again?

**Comment by ltratt** [comment]
Double hmph. I'm going to have to invoke @vext01 as I'm not sure what the right level to pull is -- sorry :/

**Comment by gabi-250** [comment]
Ha, no worries!

**Comment by ltratt** [comment]
Closing in the hope that reraising will give @gabi-250 the necessary permissions.

**Pull request closed without merging**
